<?php
/**
 * CreateShipmentRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Selling Partner API for Shipping
 *
 * Provides programmatic access to Amazon Shipping APIs.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.13
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CreateShipmentRequestTest Class Doc Comment
 *
 * @category    Class
 * @description The request schema for the createShipment operation.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CreateShipmentRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CreateShipmentRequest"
     */
    public function testCreateShipmentRequest()
    {
    }

    /**
     * Test attribute "client_reference_id"
     */
    public function testPropertyClientReferenceId()
    {
    }

    /**
     * Test attribute "ship_to"
     */
    public function testPropertyShipTo()
    {
    }

    /**
     * Test attribute "ship_from"
     */
    public function testPropertyShipFrom()
    {
    }

    /**
     * Test attribute "containers"
     */
    public function testPropertyContainers()
    {
    }
}
